Ratelimit KeyboardInterrupts to avoid double/triple signalling (#50)
When run under staticx & PyInstaller, both of them forward (some of the) signals
to gProfiler. Effectively, for a single ^C on my terminal, gProfiler gets 3
signals, as can be seen by "perf record -e signals:signal_deliver":

       gprofiler 908113 [007] 241166.780316: signal:signal_deliver: sig=2 errno=0 code=128 sa_handler=7f6804a00120 sa_flags=4000000
       gprofiler 908112 [004] 241166.780356: signal:signal_deliver: sig=2 errno=0 code=128 sa_handler=404470 sa_flags=14000000
       gprofiler 908101 [010] 241166.780356: signal:signal_deliver: sig=2 errno=0 code=128 sa_handler=400bfd sa_flags=4000000
       gprofiler 908112 [004] 241166.780394: signal:signal_deliver: sig=2 errno=0 code=0 sa_handler=404470 sa_flags=14000000
       gprofiler 908113 [007] 241166.780395: signal:signal_deliver: sig=2 errno=0 code=0 sa_handler=7f6804a00120 sa_flags=4000000
       gprofiler 908113 [007] 241166.780419: signal:signal_deliver: sig=2 errno=0 code=0 sa_handler=7f6804a00120 sa_flags=4000000

* 908101 is the staticx bootloader.
* 908112 is the PyInstaller bootloader.
* 908113 is gProfiler.

1. We can see that each of them got the SIGINT initially
2. Then PyInstaller got it again - forwarded by staticx
3. Then gProfiler got 2 more SIGINTs - one by PyInstaller, and another one for the signal
   forwarded from staticx.

This led to exceptions like:

    ^C[2021-04-29 12:47:45,670] ERROR: gprofiler: Profiling run failed!
    Traceback (most recent call last):
      File "threading.py", line 295, in wait
    KeyboardInterrupt

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "threading.py", line 551, in wait
      File "threading.py", line 295, in wait
    KeyboardInterrupt

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "gprofiler/main.py", line 178, in run_continuous
        self._snapshot()
      File "gprofiler/main.py", line 144, in _snapshot
        for future in concurrent.futures.as_completed([java_future, python_future]):
      File "concurrent/futures/_base.py", line 240, in as_completed
      File "threading.py", line 552, in wait
      File "threading.py", line 243, in __exit__
    RuntimeError: release unlocked lock

Because we got the KeyboardInterrupt more than once, and Python didn't like it.

This commit solves the problem by ratelimiting the SIGINTs we get to one per 0.5s
(although now, we should exit on the first one anyway...)

PyInstaller has --bootloader-ignore-signals which can disable that behavior, but staticx
doesn't have it. Also, it's nice if we can get signals from any of them...
So I took this approach.